image:
  name: atlassian/default-image:2

test: &test
  step:
    name: Test
    image: python:3.7
    script:
    - pip install pytest docker bitbucket_pipes_toolkit
    - pytest test/test.py --junitxml=test-reports/report.xml -v
    services:
    - docker

push: &push
  step:
    name: Push and Tag
    image: python:3.6.7
    script:
    - pip install semversioner==0.6.16
    - ./ci-scripts/bump-version.sh
    - ./ci-scripts/docker-release.sh $DOCKERHUB_USERNAME/$BITBUCKET_REPO_SLUG
    - ./ci-scripts/git-push.sh
    services:
    - docker

pipelines:
  default:
  - <<: *test
  branches:
    master:
    - <<: *test
    - <<: *push
