image:
  name: alpine/git:1.0.26

pipelines:
  default:
    - step:
        #clone:
        #  depth: full
        script:
          - git remote add github "git@github.com:thboudale/ssh-run-fork.git"
          - git checkout $BITBUCKET_BRANCH
          - git pull
          - git push github $BITBUCKET_BRANCH