image:
  name: python:3.7

test: &test
  parallel:
    - step:
        name: Test
        script:
        - pip install -r test/requirements.txt
        - pytest test/test.py --verbose --capture=no -p no:cacheprovider
        services:
        - docker
    - step:
        name: Lint the Dockerfile
        image: hadolint/hadolint:latest-debian
        script:
          - hadolint Dockerfile


release-dev: &release-dev
  step:
    name: Release development version
    image: python:3.7
    trigger: manual
    script:
      - pip install semversioner
      - VERSION=$(semversioner current-version).${BITBUCKET_BUILD_NUMBER}-dev
      - pipe: atlassian/bitbucket-pipe-release:4.2.0
        variables:
          DOCKERHUB_USERNAME: $DOCKERHUB_USERNAME
          DOCKERHUB_PASSWORD: $DOCKERHUB_PASSWORD
          IMAGE: bitbucketpipelines/$BITBUCKET_REPO_SLUG
          GIT_PUSH: 'false'
          VERSION: ${VERSION}
    services:
      - docker


push: &push
  step:
    name: Push and Tag
    image: python:3.7
    script:
    - pipe: atlassian/bitbucket-pipe-release:4.2.0
      variables:
        DOCKERHUB_USERNAME: $DOCKERHUB_USERNAME
        DOCKERHUB_PASSWORD: $DOCKERHUB_PASSWORD
        IMAGE: bitbucketpipelines/$BITBUCKET_REPO_SLUG
  services:
    - docker


pipelines:
  default:
  - <<: *test
  - <<: *release-dev
  branches:
    master:
    - <<: *test
    - <<: *push
